# This file is autogenerated by the flake.nix file, do not edit
source "https://rubygems.org"
# gemspec

# Gems dependencies to be installed
gem "jekyll-paginate", "~> 1.1.0"
gem "jekyll-sitemap", "~> 1.4.0"

gem "html-proofer", "~> 5.0", group: :test

# Github Pages plugins
group :jekyll_plugins do

end

